spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
    password: root
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
s3:
  endpointUrl: http://127.0.0.1:9000
  accessKey: 33VT03E3OI1FOYAT1TG1
  secretKey: wrA6yvx1EdOObwHvinUR6i9tGIzcdf8IT5nz0LMJ
  bucketName: moviefun
